/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2025-07-02-1b80fa3"
#endif /* AVUTIL_FFVERSION_H */
